# MoveIt-specific simulation settings
moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
jaka_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    gains:
        joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
        joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
        joint3: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
        joint4: { p: 10, d: 1, i: 0.01, i_clamp: 1 }
        joint5: { p: 10, d: 1, i: 0.01, i_clamp: 1 }
        joint6: { p: 5, d: 0.1, i: 0.0, i_clamp: 1 }

    constraints:
        goal_time: 2.0
    state_publish_rate: 50

controller_list:
    - name: jaka_arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6